### PR TITLE
Add itens name extra on world

### PR DESCRIPTION
**Pull request by nicolasmenegoni**
I don't know what you will think of it from a realistic point of view .. But the gameplay is much faster

sa-mp-013

### CODE REVIEW

**Comment by Southclaws** [comment]
This was something I always debated. It's a balance of game design and something called "Expectation driven design".

Of course games aren't meant to be "realistic" but elements from real life can be taken to create challenging mechanics in games.

The design with this was to provides two pieces of information about an item, at two different levels of detail:

1. What the item _is_
2. Details about the item

From a distance, you can tell what something is. If I see a pistol on the ground, I know it's a pistol, so the `Text3D` component creates an approximate substitute for this real-life ability for humans to quickly identify objects by their shape. Which compensates for the fact that 1. your camera is much lower resolution than your human eyes and 2. objects lack detail in such an old game. This is the **low detail** level of information that's visible on an item.

So I can see objects and know what they are, but I can't _really_ tell whether a pistol is loaded just by looking at it so I have to pick it up, feel how heavy it is, maybe check the magazine or receiver. By omitting this information from the _low detail_ level of information, we create a new gameplay mechanic which is an approximate substitute for picking something up and inspecting it further to learn more about the item. This is the **high detail** level of information that's discoverable from inspecting a specific item further.

Of course this abstraction isn't perfect. If I picked up a pistol and found it had 9 rounds in the magazine, I'd remember that when I put it down again. This particular feature of human memory obviously isn't modelled in-game so this is where the abstraction breaks down.

But hopefully that serves as a decent explanation behind my game design thinking in regards to how labels work.

**Comment by Southclaws** [comment]
Maybe this can be an option server owners can toggle? I probably shouldn't be _as_ opinionated since I don't run the game any more, but I do try to keep the design close to my original vision for the game.

**Comment by nicolasmenegoni** [comment]
Understood. then it would be better to reveal this information in a textdraw when picking up the item ..

**Comment by Southclaws** [comment]
> Understood. then it would be better to reveal this information in a textdraw when picking up the item ..

Yeah this is actually a good idea, an `ActionText` when you pick up the item would be good.

> "Picked up Tec 9 (28/0, 9mm, Hollow Point)"

**Comment by Southclaws** [comment]
This is probably best as a PR to https://github.com/ScavengeSurvive/item/

**Pull request closed without merging**
