### PR TITLE
Server List Page

### PR DESCRIPTION
**Pull request by VIRUXE**
A page that lists the current online scavenge and survive servers.

### CODE REVIEW

**Review by Southclaws — APPROVED** [review]

**Comment by Southclaws** [comment]
Vercel preview fails due to outdated node version:

> Node.js Version "12.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.

**Comment by VIRUXE** [comment]
Will look into it

**Comment by VIRUXE** [comment]
> Vercel preview fails due to outdated node version:
> 
> > Node.js Version "12.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.

Will look into it

**Review by Southclaws — APPROVED** [review]

**Comment by Southclaws** [comment]
Ready to merge whenever you're happy with it

**Comment by VIRUXE** [comment]
You can merge it. Thank you

**Pull request merged**
